--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-13-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA_BOARD
--------------------------------------------------------

  CREATE TABLE "FIREWORK"."QNA_BOARD" 
   (	"QNA_NO" NUMBER, 
	"QNA_SUBJECT" VARCHAR2(50 BYTE), 
	"M_ID" VARCHAR2(10 BYTE), 
	"QNA_CONTENT" VARCHAR2(1000 BYTE), 
	"QNA_SECRET" VARCHAR2(20 BYTE), 
	"QNA_CATEGORY" VARCHAR2(20 BYTE), 
	"QNA_DATE" DATE, 
	"QNA_READCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FIREWORK.QNA_BOARD
SET DEFINE OFF;
Insert into FIREWORK.QNA_BOARD (QNA_NO,QNA_SUBJECT,M_ID,QNA_CONTENT,QNA_SECRET,QNA_CATEGORY,QNA_DATE,QNA_READCOUNT) values (59,'물병주세요','id001','백원에 파세요','n','상품문의',to_date('16/09/02','RR/MM/DD'),906);
Insert into FIREWORK.QNA_BOARD (QNA_NO,QNA_SUBJECT,M_ID,QNA_CONTENT,QNA_SECRET,QNA_CATEGORY,QNA_DATE,QNA_READCOUNT) values (57,'물병주세요','id001','백원에 파세요','n','상품문의',to_date('16/09/02','RR/MM/DD'),10);
Insert into FIREWORK.QNA_BOARD (QNA_NO,QNA_SUBJECT,M_ID,QNA_CONTENT,QNA_SECRET,QNA_CATEGORY,QNA_DATE,QNA_READCOUNT) values (55,'dd','id001','dddd','n','상품문의',to_date('16/09/01','RR/MM/DD'),1);
Insert into FIREWORK.QNA_BOARD (QNA_NO,QNA_SUBJECT,M_ID,QNA_CONTENT,QNA_SECRET,QNA_CATEGORY,QNA_DATE,QNA_READCOUNT) values (53,'ㄴ','id001','ㄴ','n','상품문의',to_date('16/09/01','RR/MM/DD'),0);
Insert into FIREWORK.QNA_BOARD (QNA_NO,QNA_SUBJECT,M_ID,QNA_CONTENT,QNA_SECRET,QNA_CATEGORY,QNA_DATE,QNA_READCOUNT) values (61,'ddd','id001','dd','n','상품문의',to_date('16/09/13','RR/MM/DD'),2);
Insert into FIREWORK.QNA_BOARD (QNA_NO,QNA_SUBJECT,M_ID,QNA_CONTENT,QNA_SECRET,QNA_CATEGORY,QNA_DATE,QNA_READCOUNT) values (63,'ddd','id001','ddd','n','상품문의',to_date('16/09/13','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index QNA_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIREWORK"."QNA_BOARD_PK" ON "FIREWORK"."QNA_BOARD" ("QNA_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QNA_BOARD
--------------------------------------------------------

  ALTER TABLE "FIREWORK"."QNA_BOARD" MODIFY ("QNA_NO" NOT NULL ENABLE);
